import { mergeConfig, defineConfig } from "vite";
import { visualizer } from "rollup-plugin-visualizer";
import { version } from "./package.json";
import fs from "fs";
import path from "path";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
// import { minifyTemplateLiterals } from "rollup-plugin-minify-template-literals";
// import { minify } from 'rollup-plugin-esbuild-minify';

const shouldAnalyze = process.env.ANALYZE === "true";
const buildFormat = process.env.BUILD_FORMAT || "es";
const isUmd = buildFormat === "umd";

const banner = `
/*!
   * New York State Design System v${version}
   * Description: A design system for New York State's digital products.
   * Repository: https://github.com/its-hcd/nysds
   * License: MIT
 */
`;

// Externalize Lit for every build.
const externalLit = (id) => id === "lit" || id.startsWith("lit/");
// Per-package library builds ALSO externalize published NYSDS sibling packages
// (@nysds/nys-*), so a component references its siblings (e.g. the internal
// <nys-label>/<nys-errormessage> a form control self-registers) at runtime instead
// of bundling duplicate copies into every package. @nysds/internals is intentionally
// NOT externalized — it is a private, unpublished module that must be inlined into
// each consumer bundle.
const externalEs = (id) => externalLit(id) || id.startsWith("@nysds/nys-");

// Plugin to remove demo HTML files after build
function removeDemoFiles() {
  return {
    name: "remove-demo-files",
    closeBundle() {
      const demoFolder = path.resolve("dist/nys-stepper");

      if (fs.existsSync(demoFolder)) {
        fs.rmSync(demoFolder, { recursive: true, force: true });
        console.log(`✓ Removed demo directory: dist/nys-stepper/`);
      }
    },
  };
}

export function copyIconAssets() {
  return {
    name: "copy-icon-assets",
    closeBundle() {
      const srcDir = path.resolve(__dirname, "./packages/nys-icon/dist/icons");
      const destDir = path.resolve("dist/icons");

      if (!fs.existsSync(srcDir)) {
        console.warn(`⚠ Icon source not found: ${srcDir} (run nys-icon build first)`);
        return;
      }

      fs.mkdirSync(destDir, { recursive: true });
      for (const file of fs.readdirSync(srcDir)) {
        fs.copyFileSync(path.join(srcDir, file), path.join(destDir, file));
      }
      console.log(`✓ Copied icon assets to dist/icons/`);
    },
  };
}


export function extractIcons() {
  return {
    name: "extract-icons",
    closeBundle() {
      const __dirname = dirname(fileURLToPath(import.meta.url));
      const srcFile = resolve(__dirname, "./packages/nys-icon/src/nys-icon.library.ts");
      const outDir = resolve(__dirname, "./packages/nys-icon/dist/icons");

      const source = readFileSync(srcFile, "utf8");

      // Match each icon entry: iconName: `<svg...>...</svg>`,
      // Allow optional whitespace between </svg> and the closing backtick,
      // since some entries have a newline before the backtick.
      const iconRegex = /(\w+):\s*`(<svg[\s\S]*?<\/svg>)\s*`/g;
      let match;
      const names = [];

      if (!existsSync(outDir)) {
        mkdirSync(outDir, { recursive: true });
      }

      while ((match = iconRegex.exec(source)) !== null) {
        const [, name, svg] = match;
        // Clean up leading whitespace from template literal indentation
        const cleaned = svg.replace(/^\s+/gm, "").trim();
        writeFileSync(resolve(outDir, `${name}.svg`), cleaned, "utf8");
        names.push(name);
      }

      // Write manifest with sorted icon names
      writeFileSync(
        resolve(outDir, "manifest.json"),
        JSON.stringify({ icons: names.sort() }, null, 2),
        "utf8",
      );

      console.log(`Extracted ${names.length} icons to dist/icons/`);
    },
  };
}


// Shared base config — exported for component packages to extend via mergeConfig
export const defaultConfig = {
  css: {
    postcss: null,
  },
  esbuild: {
    legalComments: 'inline',
  },
  build: {
    lib: {
      entry: ["./src/index.ts"],
      fileName: () => "nysds.es.js",
      formats: ["es"],
    },
    minify: 'esbuild',
    sourcemap: true,
    emptyOutDir: false, // Preserves .d.ts files generated by tsc
    rollupOptions: {
      onwarn(warning, defaultHandler) {
        if (
          warning.code === "INVALID_ANNOTATION" &&
          warning.message.includes("@stencil/core")
        ) {
          return;
        }
        defaultHandler(warning);
      },
      external: externalEs,
      output: {
        compact: true,
        banner,
        dir: "dist",
        globals: {
          lit: "Lit",
        },
      },
      plugins: [
        shouldAnalyze &&
          visualizer({ filename: "dist/stats-es.html", open: true }),
        removeDemoFiles(),
      ].filter(Boolean),
    },
  },
};

// One rollup entry per custom-element source file in a component package.
// The entry named after the package builds from src/index.ts, so the package's
// "." export (dist/<package>.js) keeps its historical file name and still
// registers every element in the package. Sibling element files (e.g.
// nys-accordionitem.ts) become their own entries so each element is
// individually importable via the package.json "exports" subpaths
// (kept in sync by src/scripts/sync-package-exports.mjs).
export function packageEntries(pkgDir) {
  const pkgName = path.basename(pkgDir); // e.g. "nys-accordion"
  const srcDir = path.join(pkgDir, "src");
  const entries = {};

  const indexFile = path.join(srcDir, "index.ts");
  entries[pkgName] = fs.existsSync(indexFile)
    ? indexFile
    : path.join(srcDir, `${pkgName}.ts`);

  for (const file of fs.readdirSync(srcDir)) {
    // Matches nys-<element>.ts only — the single dot in ".ts$" excludes
    // .test.ts / .stories.ts / .figma.ts / *.logo.ts partials.
    const match = file.match(/^(nys-[a-z0-9-]+)\.ts$/);
    if (!match || match[1] === pkgName) continue;
    entries[match[1]] = path.join(srcDir, file);
  }

  return entries;
}

// Full config for a component package build. Replaces the old per-package
// mergeConfig(defaultConfig, { build: { lib: { fileName } } }) pattern:
// build.lib is assigned after the merge because vite's mergeConfig
// concatenates arrays, which would corrupt the multi-entry object with
// defaultConfig's entry array.
export function definePackageConfig(pkgConfigUrl, { banner = "", rollupPlugins = [] } = {}) {
  const pkgDir = dirname(fileURLToPath(pkgConfigUrl));
  const merged = mergeConfig(defaultConfig, {
    build: {
      rollupOptions: {
        output: {
          banner,
          chunkFileNames: "chunks/[name]-[hash].js",
        },
        plugins: rollupPlugins,
      },
    },
  });
  merged.build.lib = {
    entry: packageEntries(pkgDir),
    fileName: (_format, entryName) => `${entryName}.js`,
    formats: ["es"],
  };
  return merged;
}

// Root build: switch between ES and UMD via BUILD_FORMAT env var.
// UMD config is constructed explicitly (not via mergeConfig) to avoid
// array-merging pitfalls with plugins and external.
export default isUmd
  ? defineConfig({
      css: {
        postcss: null,
      },
      esbuild: {
        legalComments: 'inline',
      },
      build: {
        lib: {
          entry: ["./src/index.ts"],
          name: "NYSDS", // Global variable for UMD
          fileName: () => "nysds.js",
          formats: ["umd"],
        },
        minify: 'esbuild',
        sourcemap: true,
        emptyOutDir: false,
        rollupOptions: {
          onwarn(warning, defaultHandler) {
            if (
              warning.code === "INVALID_ANNOTATION" &&
              warning.message.includes("@stencil/core")
            ) {
              return;
            }
            defaultHandler(warning);
          },
          external: [], // Bundle all dependencies including Lit
          output: {
            compact: true,
            banner,
            globals: {
              lit: "Lit",
            },
          },
          plugins: [
            shouldAnalyze &&
              visualizer({ filename: "dist/stats-umd.html", open: true }),
            removeDemoFiles(),
            copyIconAssets(),
          ].filter(Boolean),
        },
      },
    })
  : mergeConfig(defaultConfig, {
      build: {
        rollupOptions: {
          // The root bundle (nysds.es.js) is self-contained — it bundles every
          // component — so it must NOT externalize @nysds/nys-* siblings, only Lit.
          external: externalLit,
          plugins: [copyIconAssets()],
        },
      },
    });
