import { mergeConfig, defineConfig } from "vite";
import { visualizer } from "rollup-plugin-visualizer";
import fs from "fs";
import path from "path";
import { version } from "./package.json";

// import { minifyTemplateLiterals } from "rollup-plugin-minify-template-literals";
// import { minify } from 'rollup-plugin-esbuild-minify';

const shouldAnalyze = process.env.ANALYZE === "true";
const buildFormat = process.env.BUILD_FORMAT || "es";
const isUmd = buildFormat === "umd";

const banner = `
/*!
   * New York State Design System v${version}
   * Description: A design system for New York State's digital products.
   * Repository: https://github.com/its-hcd/nysds
   * License: MIT
 */
`;

// Externalize Lit and all NYSDS internal packages
const externalEs = (id) => id === "lit" || id.startsWith("lit/");

// Plugin to remove demo HTML files after build
function removeDemoFiles() {
  return {
    name: "remove-demo-files",
    closeBundle() {
      const demoFolder = path.resolve("dist/nys-stepper");

      if (fs.existsSync(demoFolder)) {
        fs.rmSync(demoFolder, { recursive: true, force: true });
        console.log(`✓ Removed demo directory: dist/nys-stepper/`);
      }
    },
  };
}

// Shared base config — exported for component packages to extend via mergeConfig
export const defaultConfig = {
  css: {
    postcss: null,
  },
  esbuild: {
    legalComments: 'inline',
  },
  build: {
    lib: {
      entry: ["./src/index.ts"],
      fileName: () => "nysds.es.js",
      formats: ["es"],
    },
    minify: 'esbuild',
    sourcemap: true,
    emptyOutDir: false, // Preserves .d.ts files generated by tsc
    rollupOptions: {
      onwarn(warning, defaultHandler) {
        if (
          warning.code === "INVALID_ANNOTATION" &&
          warning.message.includes("@stencil/core")
        ) {
          return;
        }
        defaultHandler(warning);
      },
      external: externalEs,
      output: {
        compact: true,
        banner,
        dir: "dist",
        globals: {
          lit: "Lit",
        },
      },
      plugins: [
        shouldAnalyze &&
          visualizer({ filename: "dist/stats-es.html", open: true }),
        removeDemoFiles(), // Add the cleanup plugin
      ].filter(Boolean),
    },
  },
};

// Root build: switch between ES and UMD via BUILD_FORMAT env var.
// UMD config is constructed explicitly (not via mergeConfig) to avoid
// array-merging pitfalls with plugins and external.
export default isUmd
  ? defineConfig({
      css: {
        postcss: null,
      },
      esbuild: {
        legalComments: 'inline',
      },
      build: {
        lib: {
          entry: ["./src/index.ts"],
          name: "NYSDS", // Global variable for UMD
          fileName: () => "nysds.js",
          formats: ["umd"],
        },
        minify: 'esbuild',
        sourcemap: true,
        emptyOutDir: false,
        rollupOptions: {
          onwarn(warning, defaultHandler) {
            if (
              warning.code === "INVALID_ANNOTATION" &&
              warning.message.includes("@stencil/core")
            ) {
              return;
            }
            defaultHandler(warning);
          },
          external: [], // Bundle all dependencies including Lit
          output: {
            compact: true,
            banner,
            globals: {
              lit: "Lit",
            },
          },
          plugins: [
            shouldAnalyze &&
              visualizer({ filename: "dist/stats-umd.html", open: true }),
            removeDemoFiles(),
          ].filter(Boolean),
        },
      },
    })
  : mergeConfig(defaultConfig, {});
