title: "Component proposal: [Component name]"
labels: ["Type: New component proposal"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new component for the New York State Design System (NYSDS)!

        To get the discussion started, you just need to fill out the three fields marked with an asterisk (*). Then collaborate with the community to add supporting evidence and research, and get feedback. The work you do now can help the NYSDS team create a formal component proposal.

        ## The Basics
  - type: textarea
    id: name
    attributes:
      label: Component name
      description: |
        Share the common name (or names) for this component.
      value:
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Component description
      description: |
        Briefly tell us the purpose of this component.
      value:
    validations:
      required: true
  - type: textarea
    id: need
    attributes:
      label: Why the NYS Design System needs this component
      description: |
        Include key interactions, current gaps in NYS Design System, and the problems this component solves. Explain how the component supports state laws, guidance, or policies.
      value:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Component details
  - type: textarea
    id: api
    attributes:
      label: Component API
      description: |
        List the props, slots, and events for each component element.
        Please format as:
        - propName (type) – Description (e.g. "required (boolean) – Marks field as required")
        - slotName – Description
        - nysCustomEventName – Description
      value:
    validations:
      required: false
  - type: textarea
    id: behavior
    attributes:
      label: Functionality and behavior
      description: |
        Describe component behavior, edge cases, and interactions. Include any special considerations for mobile or desktop (responsiveness).
        Include any min/max usage recommendations.
      value:
    validations:
      required: false
  - type: textarea
    id: decisions
    attributes:
      label: Team Decisions (for NYSDS team use)
      description: |
        Document decisions made by the team during the proposal meeting of "to do" and "what not to do."
        Example:
        - Don’t show nested steps
        - Only support linear flows
        - Use discrete steps instead of a continuous progress bar
        - Button slot sticks to the top on scroll
      value:
    validations:
      required: false
  - type: textarea
    id: questions
    attributes:
      label: Outstanding Questions
      description: |
        List open questions for the feedback window. These may need design input, dev review, or user research.
        Example:
        - Should we support optional steps that users can skip?
        - Should we show descriptions under step labels?
      value:
    validations:
      required: false
  - type: textarea
    id: references
    attributes:
      label: Outside References
      description: |
        Link to comparable components or design systems (e.g. USWDS, Shoelace, Material, etc).
        Include links/screenshots to any relevant research, user testing, or other supporting evidence.
      value:
    validations:
      required: false
  - type: textarea
    id: mockups
    attributes:
      label: Mockups (for NYSDS team use)
      description: |
        Prototype or mockup of the component, if available. This can be a link to a Figma file, a screenshot, or a description of the design.
      value:
    validations:
      required: false
  - type: textarea
    id: accessibility
    attributes:
      label: Accessibility considerations
      description: |
        Include how this component interacts with assistive technologies such as keyboard navigation, screen readers, zoom magnification, and voice command. Are there audiences that might struggle with this component? How might the component become inaccessible?
      value:
    validations:
      required: false
  - type: textarea
    id: involved
    attributes:
      label: Who's involved
      description: |
        Please tag volunteers who may be willing to help design, develop or test this component. Note agencies that can offer significant support for the component, and tag any stakeholders. Be sure to share a list of those who helped research and prepare this proposal. Include your name and/or GitHub username if you'd like credit as a contributor.
      value:
    validations:
      required: false
