title: "Feature proposal: [Feature name]"
labels: ["Type: New feature proposal"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature for Excelsior Design System.
        
        To get the discussion started, you just need to fill out the three fields marked with an asterisk (*). Then collaborate with the community to add supporting evidence and research, and get feedback. The work you do now can help the team create a formal feature proposal.
        
        [Learn more about the feature proposal process](https://github.com/uswds/uswds/discussions/5764).
        
        ## The basics
  - type: textarea
    id: name
    attributes:
      label: Feature name
      description: |
        Share the common name (or names) for this feature.
      value:
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 'Feature description'
      description: |
        Briefly tell us the purpose of this feature.
      value:
    validations:
      required: true
  - type: textarea
    id: need
    attributes:
      label: 'Why Excelsior needs this feature'
      description: |
        Include key interactions, current gaps in Excelsior, and the problems this feature solves. Explain how the feature supports state laws, guidance, or policies.
      value:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Feature details
  - type: textarea
    id: design
    attributes:
      label: 'How the feature works'
      description: |
        Describe how the feature works. Include any interactive states and variants. Diagrams, images, wireframes, and prototypes can help you make your case.
      value:
    validations:
      required: false
  - type: textarea
    id: implementation
    attributes:
      label: 'Real-world examples'
      description: |
        Link to examples of other sites — preferably government sites — that use this kind of feature.
      value:
    validations:
      required: false
  - type: textarea
    id: when_to_use
    attributes:
      label: When to use this feature and when to consider something else
      description: |
        What kind of content works best with this feature, and what kind of content would work poorly with it? What are common misuses of this type of feature?
      value:
    validations:
      required: false
  - type: textarea
    id: usability
    attributes:
      label: Usability considerations
      description: |
        Include conditions that would make this feature more usable or less usable. Also include common pitfalls or implementation mistakes associated with this feature.
      value:
    validations:
      required: false
  - type: textarea
    id: accessibility
    attributes:
      label: Accessibility considerations
      description: |
        Include how this feature interacts with assistive technologies such as keyboard navigation, screen readers, zoom magnification, and voice command. Are there audiences that might struggle with this feature? How might the feature become inaccessible?
      value:
    validations:
      required: false
  - type: textarea
    id: involved
    attributes:
      label: Who’s involved
      description: |
        Please tag volunteers who may be willing to help design, develop or test this feature. Note agencies that can offer significant support for the feature, and tag any stakeholders. Be sure to share a list of those who helped research and prepare this proposal. Include your name and/or GitHub username if you’d like credit as a contributor.
      value:
    validations:
      required: false
