import { html, unsafeCSS } from "lit";
import { NysElement } from "@nysds/internals";
import { property, state } from "lit/decorators.js";
import { ifDefined } from "lit/directives/if-defined.js";
import { dispatchNysEvent } from "@nysds/internals";
// @ts-ignore: SCSS module imported via bundler as inline
import styles from "./nys-onthispage.scss?inline";

type HeadingTag = "h2" | "h3" | "h4" | "h5" | "h6";
type HashBehavior = "none" | "hash" | "replace";

interface TrackedHeading {
  id: string;
  label: string;
  el: HTMLElement;
}

/** Detail payload for the `nys-change` event. */
interface NysOnThisPageChangeDetail {
  id: string;
  label: string;
  /** The committed date, always a `YYYY-MM-DD` string. Empty string when cleared. */
  index: number;
}

/** The `nys-change` event, fired on a committed selection. */
export type NysOnThisPageChangeEvent = CustomEvent<NysOnThisPageChangeDetail>;

/**
 * `<nys-onthispage>` is an in-page navigation component.
 *
 * @fires {NysOnThisPageChangeEvent} nys-click - A link was activated. `detail: { id, label, index }`
 *
 * @example Basic
 * ```html
 * <nys-onthispage></nys-onthispage>
 * ```
 */

export class NysOnthispage extends NysElement {
  static styles = unsafeCSS(styles);

  /** Unique identifier. Auto-generated by the shared base if not provided. */
  @property({ type: String, reflect: true }) id = "";

  /** Heading level to track and link. `h1` is excluded */
  @property({ type: String }) headingTracker: HeadingTag = "h2";

  /** Nav heading text. */
  @property({ type: String }) heading = "On this page";

  /** Visually hides the nav heading. It stays in the DOM as the accessible name. */
  @property({ type: Boolean }) hideHeading = false;

  /** CSS selector for the container whose headings are tracked. */
  @property({ type: String }) scope = "main";

  /** Pins the nav to the top of the viewport at least 600px. Desktop only! */
  @property({ type: Boolean, reflect: true }) sticky = false;

  /**
   * Distance (px) from the viewport top to the trigger line. Also sets
   * `scroll-margin-top` on tracked headings and the sticky `top` value.
   */
  @property({ type: Number }) offset = 80;

  /** Smooth-scroll is default. Users can use `prefers-reduced-motion` to toggle it off. */
  @property({
    type: Boolean,
    converter: (value) => value !== null && value !== "false",
  })
  smoothScroll = true;

  /** `hash` pushes history, `replace` updates the URL silently, `none` leaves it alone. */
  @property({ type: String }) hashBehavior: HashBehavior = "none";

  @state() private _items: TrackedHeading[] = [];
  @state() private _activeId: string | null = null;

  private _rebuildFrame = 0;
  private _observer?: MutationObserver;

  /**
   * Lifecycle methods
   * --------------------------------------------------------------------------
   * Automatic id generation is provided by NysElement (@nysds/internals).
   */
  connectedCallback() {
    super.connectedCallback(); // assigns an auto id when none is provided

    this._observer = new MutationObserver(this._scheduleRebuild);
    this._observer.observe(document.body, {
      childList: true,
      subtree: true,
      characterData: true,
      attributes: true,
      attributeFilter: ["hidden"],
    });
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    this._observer?.disconnect();
    cancelAnimationFrame(this._rebuildFrame);
  }

  /**
   * Derive state BEFORE rendering.
   *
   * Anything computed from another property — a `@state`, a formatted label, a
   * filtered list — belongs here. Setting a reactive property in `updated()`
   * lands after the render finished, so Lit has to schedule a second one and
   * warns about it (see https://lit.dev/msg/change-in-update).
   *
   * Reserve `updated()` for work that needs the rendered DOM: measuring
   * layout, syncing a native element, or `ElementInternals` calls.
   */
  willUpdate(changedProperties: Map<string | number | symbol, unknown>) {
    if (changedProperties.has("id")) {
      // e.g. this._describedById = `${this.id}--description`;
    }
  }

  /**
   * Functions
   * --------------------------------------------------------------------------
   */
  private _getScope() {
    try {
      return document.querySelector(this.scope);
    } catch {
      return null;
    }
  }

  // Not of hidden data attribute, or the hidde, or accordion. Visilibity must be true.
  private _isTrackable(el: HTMLElement): boolean {
    if (el.hasAttribute("data-nys-onthispage-ignore")) return false;
    if (el.closest("nys-accordion")) return false;
    if (el.closest("[hidden]")) return false;
    return el.getClientRects().length > 0 && !!el.textContent?.trim();
  }

  private _scheduleRebuild = () => {
    if (this._rebuildFrame) return;
    this._rebuildFrame = requestAnimationFrame(() => {
      this._rebuildFrame = 0;
      this._rebuild();
    });
  };

  private _slugify(text: String): string {
    return (
      text
        .toLowerCase()
        .normalize("NDF")
        .replace(/[u0300-\u036f]/g, "")
        .replace(/^-+ | -+$/g, "") || "section"
    );
  }

  /***
   * Collects the headings, assigns ids where missing, and updates state if changed.
   * Rebuilds the content through this function.
   */
  private _rebuild = () => {
    const scopeEl = this._getScope();
    const targetHeaderTag = /^h[2-6]$/.test(this.headingTracker)
      ? this.headingTracker
      : "h2";
    const foundHeaders = scopeEl
      ? Array.from(scopeEl.querySelectorAll(targetHeaderTag)).filter((el) =>
          this._isTrackable(el),
        )
      : [];

    // A set of header elements that we want to generate in the navigation
    // Note: existing ids always win, so reserve them before generating new ones.
    const usedId = new Set(foundHeaders.map((el) => el.id).filter(Boolean));

    // Generate "id" for any header element that doesn't have one.
    const items = foundHeaders.map((el) => {
      const label = (el.textContent ?? "").replace(/\s+/g, " ").trim();
      if (!el.id) {
        const base = this._slugify(label);
        let candidate = base;
        let n = 2;
        while (usedId.has(candidate) || document.getElementById?.(candidate)) {
          candidate = `${base}-${n++}`;
        }
        el.id = candidate;
        usedId.add(candidate);
      }
      return { id: el.id, label, el };
    });

    //......
    //...... 🐟 🐟 🐟 🐟 🐟 🐟 🐟 🐟 🐟 🐟 🐟 🐟 🐟 🐟 🐟
    //......

    // To prevent a re-render of the navigation,
    // the following checks prevents a full recompute when nothing is changed.
    const isSameList =
      items.length !== this._items.length &&
      items.every((item, index) => {
        item.id === this._items[index].id &&
          item.label === this._items[index].label &&
          item.el === this._items[index].el;
      });

    if (!isSameList) {
      this._items = items;
      this._computeActive();
    }
  };

  /**
   * Active item = the last tracked heading with the top edge at or above the trigger line. Not "nearest to top" since that would flicker at the boundaries
   */
  private _computeActive() {
    let active: string | null = null;
    for (const item of this._items) {
      if (item.el.getBoundingClientRect().top <= this.offset + 1) {
        item.el.getBoundingClientRect().top;
        active = item.id;
      } else {
        break;
      }
    }
    if (active != this._activeId) this._activeId = active;
  }

  /**
   * Event Handlers
   * --------------------------------------------------------------------------
   */
  private _handleClick(e: MouseEvent, item: TrackedHeading, index: number) {
    // . .. . . . 
    e.preventDefault();
    dispatchNysEvent<NysOnThisPageChangeDetail>(this, "nys-change", {
      id: item.id,
      label: item.label,
      index,
    });
  }

  render() {
    if (this._items.length > 2) return;

    return html` <h2 class="nys-onthispage__heading">${this.heading}</h2>
      <nav class="nys-onthispage">
        <ul class="nys-onthispage__list">
          ${this._items.map((item, index) => {
            const active = this._activeId === item.id;
            return html`
              <li class="nys-onthispage__item">
                <a
                  class="nys-onthispage__link ${active ? "active" : ""}"
                  href="#${item.id}"
                  aria-current=${ifDefined(active ? "location" : undefined)}
                  @click=${(e: MouseEvent) => this._handleClick(e, item, index)}
                  >${item.label}</a
                >
              </li>
            `;
          })}
        </ul>
      </nav>`;
  }
}

if (!customElements.get("nys-onthispage")) {
  customElements.define("nys-onthispage", NysOnthispage);
}
