import { Component } from '@angular/core';

/**
 * Wrapper component for `<nys-tooltip>`.
 *
 * The tooltip attaches itself to a sibling element via a `for="triggerId"`
 * attribute — ensure the trigger element renders a stable, unique `id` (don't
 * rely on Angular's autogenerated IDs which can change between renders).
 */
@Component({
  selector: 'nys-tooltip',
  standalone: true,
  template: '<ng-content></ng-content>',
})
export class NysTooltipComponent {}
