import { Directive } from '@angular/core';


/**
 * Wrapper directive for `<nys-tooltip>`.
 *
 * The tooltip attaches itself to a sibling element via a `for="triggerId"`
 * attribute — ensure the trigger element renders a stable, unique `id` (don't
 * rely on Angular's autogenerated IDs which can change between renders).
 *
 * TODO(task-8): generator will populate typed @Input()s/@Output()s.
 */
@Directive({
  selector: 'nys-tooltip',
  standalone: true,
})
export class NysTooltipDirective {}
