name: Parent Ticket
description: Used to track a new component or feature from spike to release
title: "BUILD: [Component]"
labels: ["Proposal: Draft"]
assignees:
  - esteinborn
projects:
  - ITS-HCD/1

body:
  - type: markdown
    attributes:
      value: |
        Parent Ticket to track progress of **[COMPONENT]**

  - type: markdown
    attributes:
      value: |
        ## Timeline:

        | Sprint # | Dates     | Description                 |
        |----------|-----------|-----------------------------|
        | current  | add here  | Spike tickets and research  |
        | +1       | add here  | Feedback window open        |
        | +2       | add here  | Design phase                |
        | +3       | add here  | Develop/QA phase            |
