name: Parent Ticket
description: Used to track a new component or feature from spike to release
title: "PARENT: [Component]"
labels: ["Proposal: Draft"]
assignees:
  - esteinborn
projects:
  - ITS-HCD/1

body:
  - type: textarea
    id: parent-ticket-content
    attributes:
      label: Parent Ticket Content
      description: Please fill out the details below for tracking this component's progress.
      value: |
        Parent Ticket to track progress of COMPONENT_NAME
