/**
 * CEM plugin: generates the `@lit/react` wrapper for every NYSDS component
 * into `packages/react/src/generated/` (decision R1).
 *
 * The output directory is cleared and recreated on every run, so removed
 * components leave no orphans. A hand-written file at
 * `src/overrides/<ClassName>.ts` replaces the generated one: the component
 * is skipped and the barrel re-exports the override.
 */
import fs from "node:fs";
import path from "node:path";
import { listComponents } from "./lib/core.mjs";

/** Event interface names the platform provides; never imported. */
const GLOBAL_EVENT_TYPES = new Set([
  "Event",
  "CustomEvent",
  "UIEvent",
  "FocusEvent",
  "InputEvent",
  "KeyboardEvent",
  "MouseEvent",
  "PointerEvent",
  "TouchEvent",
  "WheelEvent",
  "AnimationEvent",
  "TransitionEvent",
  "ClipboardEvent",
  "DragEvent",
  "SubmitEvent",
]);

const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * Splits event types into locally usable text and package type imports.
 * Bare identifiers that are not platform globals are assumed to be typed
 * aliases exported by the component package (section 4.3 of the plan).
 * Anything else — including today's bare `CustomEvent` — is used verbatim.
 */
function resolveEventType(typeText) {
  if (IDENTIFIER_RE.test(typeText) && !GLOBAL_EVENT_TYPES.has(typeText)) {
    return { text: typeText, importName: typeText };
  }
  return { text: typeText, importName: undefined };
}

function renderReactWrapper(component) {
  const { tag, className, packageName, events } = component;
  const elementAlias = `${className}Element`;

  const typeImports = new Set();
  const eventLines = [];
  const seenProps = new Set();
  for (const event of events) {
    // Two event names can map to one React prop (a deprecated camelCase
    // alias like `nys-fileRemove` next to `nys-file-remove`). Keep the
    // first, which is the canonical name in manifest order.
    if (seenProps.has(event.reactProp)) continue;
    seenProps.add(event.reactProp);
    const { text, importName } = resolveEventType(event.typeText);
    if (importName) typeImports.add(importName);
    eventLines.push(`    ${event.reactProp}: "${event.name}" as EventName<${text}>,`);
  }

  const lines = [];
  lines.push(`"use client";`);
  lines.push(
    `// GENERATED by @nysds/codegen — do not edit. Override: src/overrides/${className}.ts`
  );
  lines.push(`import * as React from "react";`);
  lines.push(
    events.length > 0
      ? `import { createComponent, type EventName } from "@lit/react";`
      : `import { createComponent } from "@lit/react";`
  );
  lines.push(
    `import { ${className} as ${elementAlias} } from "${packageName}";`
  );
  if (typeImports.size > 0) {
    lines.push(
      `import type { ${[...typeImports].sort().join(", ")} } from "${packageName}";`
    );
  }
  lines.push(``);
  lines.push(`export const ${className} = createComponent({`);
  lines.push(`  react: React,`);
  lines.push(`  tagName: "${tag}",`);
  lines.push(`  elementClass: ${elementAlias},`);
  lines.push(`  displayName: "${className}",`);
  if (eventLines.length > 0) {
    lines.push(`  events: {`);
    lines.push(...eventLines);
    lines.push(`  },`);
  }
  lines.push(`});`);
  lines.push(``);
  lines.push(
    `export type ${className}Props = React.ComponentProps<typeof ${className}>;`
  );
  lines.push(`export type { ${elementAlias} };`);
  lines.push(``);
  return lines.join("\n");
}

export function reactPlugin(options = {}) {
  const {
    outDir = "packages/react/src/generated",
    overridesDir = "packages/react/src/overrides",
  } = options;

  return {
    name: "nysds-react-wrappers",

    packageLinkPhase({ customElementsManifest }) {
      const components = listComponents(customElementsManifest);
      if (components.length === 0) return;

      fs.rmSync(outDir, { recursive: true, force: true });
      fs.mkdirSync(outDir, { recursive: true });

      const barrel = [
        `// GENERATED by @nysds/codegen — do not edit.`,
      ];
      for (const component of components) {
        const overridePath = path.join(
          overridesDir,
          `${component.className}.ts`
        );
        if (fs.existsSync(overridePath)) {
          barrel.push(`export * from "../overrides/${component.className}.js";`);
          continue;
        }
        fs.writeFileSync(
          path.join(outDir, `${component.className}.ts`),
          renderReactWrapper(component)
        );
        barrel.push(`export * from "./${component.className}.js";`);
      }
      fs.writeFileSync(path.join(outDir, "index.ts"), barrel.join("\n") + "\n");
    },
  };
}
