/**
 * CEM plugin: generates the Vue typings for every NYSDS component into
 * `packages/vue/src/generated/`.
 *
 * Per component, `<ClassName>.ts` exports:
 * - `<ClassName>Props`, `<ClassName>Events`: the attributes, properties and
 *   `on<Event>` handlers a raw `<nys-*>` tag accepts.
 * - `<ClassName>Slots`: the slot names from the manifest, typed for
 *   `<template #name>` on the wrapper.
 * - `<ClassName>Model` (form controls only): `modelValue` and
 *   `onUpdate:modelValue`, derived from the `@formControl` tag.
 * - `<ClassName>`: a Vue component (built by `createNysComponent` in
 *   `src/runtime.ts`) that renders the element, maps slots to light-DOM
 *   children, and supports `v-model` on form controls.
 *
 * Plus:
 * - `index.ts` is the barrel.
 * - `global.ts` augments `vue`'s `GlobalComponents` (typed `<nys-*>` in
 *   templates via Volar / vue-tsc) and the global `JSX.IntrinsicElements`
 *   (typed `<nys-*>` in TSX/JSX).
 *
 * Prop types are picked from the element class, so they stay exact even where
 * the manifest carries only a loose type string. The output directory is
 * cleared on every run, so removed components leave no orphans.
 */
import fs from "node:fs";
import path from "node:path";
import { listComponents } from "./lib/core.mjs";
import { resolveEventType } from "./react.mjs";

function renderVueProps(component) {
  const { className, packageName, props, events, slots, formControl } =
    component;
  const elementAlias = `${className}Element`;
  const propsName = `${className}Props`;

  const typeImports = new Set();
  const eventLines = [];
  const seenProps = new Set();
  for (const event of events) {
    // Vue camelizes `@nys-change` to `onNysChange`, the same shape React
    // uses, so two event names can collide here too. Keep the first.
    if (seenProps.has(event.reactProp)) continue;
    seenProps.add(event.reactProp);
    const { text, importName } = resolveEventType(event.typeText);
    if (importName) typeImports.add(importName);
    if (event.description) {
      eventLines.push(
        `  /** ${event.description.replace(/\s*\n\s*/g, " ").replace(/\*\//g, "*\\/")} */`
      );
    }
    eventLines.push(`  ${event.reactProp}?: (event: ${text}) => void;`);
  }

  const propNames = [...new Set(props.map((prop) => prop.name))].sort();
  const propsType =
    propNames.length > 0
      ? `Partial<Pick<${elementAlias}, ${propNames.map((n) => JSON.stringify(n)).join(" | ")}>>`
      : `{}`;

  const lines = [];
  lines.push(
    `// GENERATED by @nysds/codegen — do not edit. Regenerate with \`npm run cem\`.`
  );
  lines.push(
    `import type { ${className} as ${elementAlias}${[...typeImports].sort().map((n) => `, ${n}`).join("")} } from "${packageName}";`
  );
  lines.push(`import "${packageName}";`);
  lines.push(`import type { HTMLAttributes, ReservedProps } from "vue";`);
  lines.push(
    `import { createNysComponent, type NysComponent, type NysSlots } from "../runtime.js";`
  );
  lines.push(``);
  lines.push(`/** Handlers for the events \`<${component.tag}>\` dispatches. */`);
  lines.push(`export interface ${className}Events {`);
  lines.push(...eventLines);
  lines.push(`}`);
  lines.push(``);
  lines.push(`type ${className}Members = ${propsType};`);
  lines.push(``);
  lines.push(
    `/** Everything \`<${component.tag}>\` accepts in a Vue template or TSX file. */`
  );
  lines.push(`export type ${propsName} = Omit<`);
  lines.push(`  HTMLAttributes,`);
  lines.push(`  keyof ${className}Members | keyof ${className}Events`);
  lines.push(`> &`);
  lines.push(`  ReservedProps &`);
  lines.push(`  ${className}Members &`);
  lines.push(`  ${className}Events;`);
  lines.push(``);
  lines.push(`export type { ${elementAlias} };`);
  lines.push(``);

  // Slots: "" is the default slot. The default slot is always allowed: some
  // elements take children without documenting one in the manifest.
  const slotKeys = [
    ...new Set(["default", ...slots.map((slot) => slot.name || "default")]),
  ].sort();
  lines.push(
    `/** Slots of \`<${component.tag}>\`, fillable with \`<template #name>\` on the wrapper. */`
  );
  lines.push(
    `export type ${className}SlotName = ${slotKeys.map((n) => JSON.stringify(n)).join(" | ")};`
  );
  lines.push(
    `export type ${className}Slots = NysSlots<${className}SlotName>;`
  );
  lines.push(``);

  // v-model: only where the manifest declares a form contract.
  let modelType = "";
  if (formControl) {
    const modelValueType = `${elementAlias}[${JSON.stringify(formControl.kind)}]`;
    lines.push(
      `/** \`v-model\` binds \`${formControl.kind}\`; add \`.lazy\` to update on \`${formControl.changeEvent}\`. */`
    );
    lines.push(`export interface ${className}Model {`);
    lines.push(`  modelValue?: ${modelValueType};`);
    lines.push(
      `  "onUpdate:modelValue"?: (value: ${modelValueType}) => void;`
    );
    lines.push(`}`);
    lines.push(``);
    modelType = ` & ${className}Model`;
  }

  // Runtime wrapper.
  const booleanProps = [
    ...new Set(props.filter((prop) => prop.isBoolean).map((prop) => prop.name)),
  ].sort();
  lines.push(`export const ${className} = createNysComponent<`);
  lines.push(
    `  NysComponent<${propsName}${modelType}, ${className}Slots>`
  );
  lines.push(`>({`);
  lines.push(`  tag: "${component.tag}",`);
  lines.push(`  name: "${className}",`);
  lines.push(`  props: ${JSON.stringify(propNames)},`);
  lines.push(`  booleanProps: ${JSON.stringify(booleanProps)},`);
  if (formControl) {
    const listener = (name) =>
      events.find((event) => event.name === name)?.reactProp;
    const changeListener = listener(formControl.changeEvent);
    const inputListener = formControl.inputEvent
      ? listener(formControl.inputEvent)
      : undefined;
    lines.push(`  model: {`);
    lines.push(`    kind: "${formControl.kind}",`);
    lines.push(`    changeListener: "${changeListener}",`);
    if (inputListener) lines.push(`    inputListener: "${inputListener}",`);
    lines.push(`  },`);
  }
  lines.push(`});`);
  lines.push(``);
  return lines.join("\n");
}

function renderGlobal(components) {
  const lines = [];
  lines.push(`// GENERATED by @nysds/codegen — do not edit.`);
  lines.push(`import type { DefineComponent } from "vue";`);
  // A module augmentation only resolves if the program already loads the
  // module; this import guarantees it does.
  lines.push(`import type {} from "vue/jsx-runtime";`);
  for (const c of components) {
    lines.push(`import type { ${c.className}Props } from "./${c.className}.js";`);
  }
  lines.push(``);
  lines.push(`declare module "vue" {`);
  lines.push(`  /** Typed \`<nys-*>\` tags in Vue templates (Volar / vue-tsc). */`);
  lines.push(`  interface GlobalComponents {`);
  for (const c of components) {
    lines.push(`    "${c.tag}": DefineComponent<${c.className}Props>;`);
  }
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);
  // Vue exposes JSX two ways: the global namespace (`vue/jsx`) and the
  // `vue/jsx-runtime` module (`jsxImportSource: "vue"`). Augment both.
  for (const [open, close, indent] of [
    ["declare module \"vue/jsx-runtime\" {", "}", "  "],
    ["declare global {", "}", "  "],
  ]) {
    lines.push(open);
    lines.push(`${indent}namespace JSX {`);
    lines.push(`${indent}  /** Typed \`<nys-*>\` tags in TSX / JSX. */`);
    lines.push(`${indent}  interface IntrinsicElements {`);
    for (const c of components) {
      lines.push(`${indent}    "${c.tag}": ${c.className}Props;`);
    }
    lines.push(`${indent}  }`);
    lines.push(`${indent}}`);
    lines.push(close);
    lines.push(``);
  }
  lines.push(`export {};`);
  lines.push(``);
  return lines.join("\n");
}

export function vuePlugin(options = {}) {
  const { outDir = "packages/vue/src/generated" } = options;

  return {
    name: "nysds-vue-types",

    packageLinkPhase({ customElementsManifest }) {
      const components = listComponents(customElementsManifest);
      if (components.length === 0) return;

      fs.rmSync(outDir, { recursive: true, force: true });
      fs.mkdirSync(outDir, { recursive: true });

      const barrel = [`// GENERATED by @nysds/codegen — do not edit.`];
      for (const component of components) {
        fs.writeFileSync(
          path.join(outDir, `${component.className}.ts`),
          renderVueProps(component)
        );
        barrel.push(`export * from "./${component.className}.js";`);
      }
      barrel.push(`import "./global.js";`);
      fs.writeFileSync(path.join(outDir, "global.ts"), renderGlobal(components));
      fs.writeFileSync(path.join(outDir, "index.ts"), barrel.join("\n") + "\n");
    },
  };
}
