import { LitElement, html, unsafeCSS } from "lit";
import { property } from "lit/decorators.js";
import { ifDefined } from "lit/directives/if-defined.js";
import { NysElement, dispatchNysEvent } from "@nysds/internals";
// These elements are rendered inside this component's shadow DOM, so they must
// be registered whenever nys-fileitem is used. Importing them here (intentional
// side effect) guarantees the remove button and its icon always upgrade — the
// button's accessible name lands on nys-button's real inner <button>, which
// only exists once nys-button renders.
import "@nysds/nys-icon";
import "@nysds/nys-button";
// @ts-ignore: SCSS module imported via bundler as inline
import styles from "./nys-fileitem.scss?inline";

/** Detail payload for the `nys-file-remove` event (and its deprecated `nys-fileRemove` alias). */
export interface NysFileitemFileRemoveDetail {
  filename: string;
}

/** The `nys-file-remove` event dispatched by `nys-fileitem`. */
export type NysFileitemFileRemoveEvent =
  CustomEvent<NysFileitemFileRemoveDetail>;

/**
 * **Internal component.** Displays an individual file within `nys-fileinput` with status and progress.
 *
 * Rendered automatically by `nys-fileinput` for each selected file. Shows filename, upload status
 * (pending/processing/done/error), progress bar during upload, and error messages. Remove button emits event.
 *
 * When `errorMessage` is set the text is rendered into an element with a stable id
 * (`{host id}--error`) and the item references that id via `aria-errormessage` +
 * `aria-describedby`, paired with `aria-invalid` reflecting the real status.
 *
 * @summary Internal file item display with status, progress bar, and remove action.
 * @element nys-fileitem
 *
 * @fires {NysFileitemFileRemoveEvent} nys-file-remove Fired when the remove button is clicked. Detail: `{ filename }`.
 * @fires {NysFileitemFileRemoveEvent} nys-fileRemove @deprecated 1.x alias of `nys-file-remove`, fired
 * alongside it. Listen for `nys-file-remove` instead; this name goes away in 2.0.
 */
export class NysFileItem extends NysElement {
  static styles = unsafeCSS(styles);
  static shadowRootOptions = {
    ...LitElement.shadowRootOptions,
    delegatesFocus: true,
  };

  /** Name of the file being displayed. */
  @property({ type: String }) filename = "";

  /**
   * Upload status: `pending` (queued), `processing` (uploading), `done` (complete), `error` (failed).
   * @default "pending"
   */
  @property({ type: String }) status:
    | "pending"
    | "processing"
    | "done"
    | "error" = "pending";

  /** Upload progress percentage (0-100). Only shown when status is `processing`. */
  @property({ type: Number }) progress = 0;

  /** Error message displayed when status is `error`. */
  @property({ type: String }) errorMessage = "";

  /**
   * True when this item is actually in an error state. `aria-invalid` reflects
   * this rather than being hardcoded, so a healthy item is never announced as
   * invalid.
   */
  private get _isInvalid(): boolean {
    return this.status === "error" || !!this.errorMessage;
  }

  /** True only when the error element is rendered, so the IDREF can resolve. */
  private get _hasErrorText(): boolean {
    return !!this.errorMessage;
  }

  /**
   * Stable id of the element that holds the error text. `aria-errormessage` and
   * `aria-describedby` take an IDREF, so they must point at this — never at the
   * message text itself. Derived from the host id (auto-generated by NysElement)
   * rather than the filename, which is not id-safe and not stable.
   */
  private get _errorId(): string {
    return `${this.id}--error`;
  }

  private _handleRemove() {
    const detail: NysFileitemFileRemoveDetail = { filename: this.filename };
    dispatchNysEvent(this, "nys-file-remove", detail);
    // Deprecated alias kept for 1.x listeners; remove in 2.0.
    dispatchNysEvent(this, "nys-fileRemove", detail);
  }

  private splitFilename(filename: string) {
    const lastDotIndex = filename.lastIndexOf(".");
    const extension = lastDotIndex !== -1 ? filename.slice(lastDotIndex) : ""; // e.g. ".pdf"
    const name =
      lastDotIndex !== -1 ? filename.slice(0, lastDotIndex) : filename;

    const startPart = name.slice(0, name.length - 3);
    const endPart = name.slice(-3);

    return { startPart, endPart, extension };
  }

  render() {
    const { startPart, endPart, extension } = this.splitFilename(this.filename);

    return html`
      <div
        class="file-item ${this.status}"
        aria-busy=${this.status === "processing" ? "true" : "false"}
        aria-label="You have selected ${this.filename}"
        aria-invalid=${this._isInvalid ? "true" : "false"}
        aria-errormessage=${ifDefined(
          this._hasErrorText ? this._errorId : undefined,
        )}
        aria-describedby=${ifDefined(
          this._hasErrorText ? this._errorId : undefined,
        )}
      >
        <div class="file-item__main" role="group">
          <nys-icon
            class="file-icon"
            name=${this.status === "processing"
              ? "progress_activity"
              : this.status === "error"
                ? "error"
                : "attach_file"}
            size="2xl"
          ></nys-icon>
          <div class="file-item__info">
            <div class="file-item__info-name">
              <span class="file-item__info-name-start">${startPart}</span>
              <span class="file-item__info-name-end"
                >${endPart}${extension}</span
              >
            </div>
            ${this.errorMessage
              ? html`<p
                  class="file-item__error"
                  role="alert"
                  aria-live="assertive"
                  id=${this._errorId}
                >
                  ${this.errorMessage}
                </p>`
              : null}
          </div>
          <nys-button
            circle
            icon="close"
            label="Remove file: ${this.filename}"
            size="sm"
            variant="ghost"
            @nys-click=${this._handleRemove}
          ></nys-button>
        </div>
        ${this.status === "processing"
          ? html`<div
              class="file-item__progress-container"
              role="progressbar"
              aria-valuemin="0"
              aria-valuemax="100"
              aria-valuenow="${this.progress}"
              aria-label="Upload progress for ${this.filename}"
            >
              <progress value=${this.progress} max="100"></progress>
            </div>`
          : null}
      </div>
    `;
  }
}

if (!customElements.get("nys-fileitem")) {
  customElements.define("nys-fileitem", NysFileItem);
}
