/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysVideo as NysVideoElement } from "@nysds/nys-video";
import "@nysds/nys-video";

@ProxyCmp({
  inputs: [
    "autoplay",
    "disabled",
    "id",
    "loading",
    "size",
    "starttime",
    "thumbnail",
    "titleText",
    "videourl",
  ],
})
@Component({
  selector: "nys-video",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "autoplay",
    "disabled",
    "id",
    "loading",
    "size",
    "starttime",
    "thumbnail",
    "titleText",
    "videourl",
  ],
  outputs: ["nys-video-play"],
})
export class NysVideoComponent {
  protected readonly el: NysVideoElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, ["nys-video-play"]);
  }
}

export declare interface NysVideoComponent extends Pick<
  NysVideoElement,
  | "autoplay"
  | "disabled"
  | "id"
  | "loading"
  | "size"
  | "starttime"
  | "thumbnail"
  | "titleText"
  | "videourl"
> {
  "nys-video-play": Observable<CustomEvent>;
}
