/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysProcesslist as NysProcesslistElement } from "@nysds/nys-processlist";
import "@nysds/nys-processlist";

@ProxyCmp({ inputs: ["id", "initialStep", "neutral", "size", "strong"] })
@Component({
  selector: "nys-processlist",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["id", "initialStep", "neutral", "size", "strong"],
})
export class NysProcesslistComponent {
  protected readonly el: NysProcesslistElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysProcesslistComponent extends Pick<
  NysProcesslistElement,
  "id" | "initialStep" | "neutral" | "size" | "strong"
> {}
