/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysIcon as NysIconElement } from "@nysds/nys-icon";
import "@nysds/nys-icon";

@ProxyCmp({
  inputs: [
    "ariaLabel",
    "color",
    "flip",
    "library",
    "name",
    "rotate",
    "size",
    "updateComplete",
  ],
})
@Component({
  selector: "nys-icon",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "ariaLabel",
    "color",
    "flip",
    "library",
    "name",
    "rotate",
    "size",
    "updateComplete",
  ],
})
export class NysIconComponent {
  protected readonly el: NysIconElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysIconComponent extends Pick<
  NysIconElement,
  | "ariaLabel"
  | "color"
  | "flip"
  | "library"
  | "name"
  | "rotate"
  | "size"
  | "updateComplete"
> {}
