/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysDropdownMenu as NysDropdownMenuElement } from "@nysds/nys-dropdownmenu";
import "@nysds/nys-dropdownmenu";

@ProxyCmp({ inputs: ["for", "label", "position", "showDropdown"] })
@Component({
  selector: "nys-dropdownmenu",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["for", "label", "position", "showDropdown"],
})
export class NysDropdownMenuComponent {
  protected readonly el: NysDropdownMenuElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysDropdownMenuComponent extends Pick<
  NysDropdownMenuElement,
  "for" | "label" | "position" | "showDropdown"
> {}
