/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysDropdownMenuItem as NysDropdownMenuItemElement } from "@nysds/nys-dropdownmenu/nys-dropdownmenuitem";
import "@nysds/nys-dropdownmenu/nys-dropdownmenuitem";

@ProxyCmp({
  inputs: ["disabled", "divider", "href", "label", "prefixIcon", "target"],
})
@Component({
  selector: "nys-dropdownmenuitem",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["disabled", "divider", "href", "label", "prefixIcon", "target"],
  outputs: ["nys-click"],
})
export class NysDropdownMenuItemComponent {
  protected readonly el: NysDropdownMenuItemElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, ["nys-click"]);
  }
}

export declare interface NysDropdownMenuItemComponent extends Pick<
  NysDropdownMenuItemElement,
  "disabled" | "divider" | "href" | "label" | "prefixIcon" | "target"
> {
  "nys-click": Observable<CustomEvent>;
}
