/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysIconlistitem as NysIconlistitemElement } from "@nysds/nys-iconlist/nys-iconlistitem";
import "@nysds/nys-iconlist/nys-iconlistitem";

@ProxyCmp({ inputs: ["divider", "icon"] })
@Component({
  selector: "nys-iconlistitem",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["divider", "icon"],
})
export class NysIconlistitemComponent {
  protected readonly el: NysIconlistitemElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysIconlistitemComponent extends Pick<
  NysIconlistitemElement,
  "divider" | "icon"
> {}
