/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysStep as NysStepElement } from "@nysds/nys-stepper/nys-step";
import "@nysds/nys-stepper/nys-step";

@ProxyCmp({ inputs: ["current", "href", "label", "onClick", "selected"] })
@Component({
  selector: "nys-step",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["current", "href", "label", "onClick", "selected"],
  outputs: ["nys-step-click"],
})
export class NysStepComponent {
  protected readonly el: NysStepElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, ["nys-step-click"]);
  }
}

export declare interface NysStepComponent extends Pick<
  NysStepElement,
  "current" | "href" | "label" | "onClick" | "selected"
> {
  "nys-step-click": Observable<CustomEvent>;
}
