/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysDivider as NysDividerElement } from "@nysds/nys-divider";
import "@nysds/nys-divider";

@ProxyCmp({ inputs: ["inverted", "subtle"] })
@Component({
  selector: "nys-divider",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["inverted", "subtle"],
})
export class NysDividerComponent {
  protected readonly el: NysDividerElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysDividerComponent extends Pick<
  NysDividerElement,
  "inverted" | "subtle"
> {}
