/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysVerticalnavGroup as NysVerticalnavGroupElement } from "@nysds/nys-verticalnav";
import "@nysds/nys-verticalnav";

@ProxyCmp({ inputs: ["active", "disabled", "expanded", "id", "label"] })
@Component({
  selector: "nys-verticalnavgroup",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["active", "disabled", "expanded", "id", "label"],
  outputs: ["nys-child-resize", "nys-verticalnavgroup-toggle"],
})
export class NysVerticalnavGroupComponent {
  protected readonly el: NysVerticalnavGroupElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, [
      "nys-child-resize",
      "nys-verticalnavgroup-toggle",
    ]);
  }
}

export declare interface NysVerticalnavGroupComponent extends Pick<
  NysVerticalnavGroupElement,
  "active" | "disabled" | "expanded" | "id" | "label"
> {
  "nys-child-resize": Observable<CustomEvent>;
  "nys-verticalnavgroup-toggle": Observable<CustomEvent>;
}
