/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysAvatar as NysAvatarElement } from "@nysds/nys-avatar";
import "@nysds/nys-avatar";

@ProxyCmp({
  inputs: [
    "ariaLabel",
    "color",
    "disabled",
    "icon",
    "id",
    "image",
    "initials",
    "interactive",
    "lazy",
  ],
})
@Component({
  selector: "nys-avatar",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "ariaLabel",
    "color",
    "disabled",
    "icon",
    "id",
    "image",
    "initials",
    "interactive",
    "lazy",
  ],
})
export class NysAvatarComponent {
  protected readonly el: NysAvatarElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysAvatarComponent extends Pick<
  NysAvatarElement,
  | "ariaLabel"
  | "color"
  | "disabled"
  | "icon"
  | "id"
  | "image"
  | "initials"
  | "interactive"
  | "lazy"
> {}
