/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysFileItem as NysFileItemElement } from "@nysds/nys-fileinput/nys-fileitem";
import "@nysds/nys-fileinput/nys-fileitem";

@ProxyCmp({ inputs: ["errorMessage", "filename", "progress", "status"] })
@Component({
  selector: "nys-fileitem",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["errorMessage", "filename", "progress", "status"],
  outputs: ["nys-fileRemove"],
})
export class NysFileItemComponent {
  protected readonly el: NysFileItemElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, ["nys-fileRemove"]);
  }
}

export declare interface NysFileItemComponent extends Pick<
  NysFileItemElement,
  "errorMessage" | "filename" | "progress" | "status"
> {
  "nys-fileRemove": Observable<CustomEvent>;
}
