/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysBacktotop as NysBacktotopElement } from "@nysds/nys-backtotop";
import "@nysds/nys-backtotop";

@ProxyCmp({ inputs: ["id", "position", "visible"] })
@Component({
  selector: "nys-backtotop",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["id", "position", "visible"],
})
export class NysBacktotopComponent {
  protected readonly el: NysBacktotopElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysBacktotopComponent extends Pick<
  NysBacktotopElement,
  "id" | "position" | "visible"
> {}
