/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysIconlist as NysIconlistElement } from "@nysds/nys-iconlist";
import "@nysds/nys-iconlist";

@ProxyCmp({ inputs: ["divider", "id"] })
@Component({
  selector: "nys-iconlist",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["divider", "id"],
})
export class NysIconlistComponent {
  protected readonly el: NysIconlistElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysIconlistComponent extends Pick<
  NysIconlistElement,
  "divider" | "id"
> {}
