/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  HostListener,
  NgZone,
  forwardRef,
} from "@angular/core";
import { NG_VALUE_ACCESSOR } from "@angular/forms";
import type { ControlValueAccessor } from "@angular/forms";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysRadiobutton as NysRadiobuttonElement } from "@nysds/nys-radiobutton";
import "@nysds/nys-radiobutton";

@ProxyCmp({
  inputs: [
    "checked",
    "description",
    "disabled",
    "form",
    "hideLabel",
    "id",
    "label",
    "labelledby",
    "name",
    "other",
    "required",
    "showOtherError",
    "size",
    "tile",
    "validationMessage",
    "validity",
    "value",
  ],
})
@Component({
  selector: "nys-radiobutton",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "checked",
    "description",
    "disabled",
    "form",
    "hideLabel",
    "id",
    "label",
    "labelledby",
    "name",
    "other",
    "required",
    "showOtherError",
    "size",
    "tile",
    "validationMessage",
    "validity",
    "value",
  ],
  outputs: ["nys-blur", "nys-change", "nys-focus", "nys-other-input"],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => NysRadiobuttonComponent),
      multi: true,
    },
  ],
})
export class NysRadiobuttonComponent implements ControlValueAccessor {
  protected readonly el: NysRadiobuttonElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, [
      "nys-blur",
      "nys-change",
      "nys-focus",
      "nys-other-input",
    ]);
  }

  // ControlValueAccessor — bridges Angular forms (ngModel / formControlName)
  // to the element's `checked`/`value` property and its `nys-change` event.
  private onChange: (value: any) => void = () => {};
  private onTouched: () => void = () => {};

  // ngModel on a radio holds the selected radio's *value*; each radio is
  // checked exactly when the model matches its own value (mirrors Angular's
  // native RadioControlValueAccessor).
  writeValue(value: any): void {
    this.el.checked = value === this.el.value;
  }

  registerOnChange(fn: (value: any) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.el.disabled = isDisabled;
  }

  @HostListener("nys-change")
  protected handleChangeEvent(): void {
    if (this.el.checked) {
      this.onChange(this.el.value);
    }
  }

  @HostListener("nys-blur")
  protected handleBlurEvent(): void {
    this.onTouched();
  }
}

export declare interface NysRadiobuttonComponent extends Pick<
  NysRadiobuttonElement,
  | "checked"
  | "description"
  | "disabled"
  | "form"
  | "hideLabel"
  | "id"
  | "label"
  | "labelledby"
  | "name"
  | "other"
  | "required"
  | "showOtherError"
  | "size"
  | "tile"
  | "validationMessage"
  | "validity"
  | "value"
> {
  "nys-blur": Observable<CustomEvent>;
  "nys-change": Observable<CustomEvent>;
  "nys-focus": Observable<CustomEvent>;
  "nys-other-input": Observable<CustomEvent>;
}
