/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysTabgroup as NysTabgroupElement } from "@nysds/nys-tab";
import "@nysds/nys-tab";

@ProxyCmp({ inputs: ["id", "name"] })
@Component({
  selector: "nys-tabgroup",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["id", "name"],
})
export class NysTabgroupComponent {
  protected readonly el: NysTabgroupElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysTabgroupComponent extends Pick<
  NysTabgroupElement,
  "id" | "name"
> {}
