/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysProcesslistitem as NysProcesslistitemElement } from "@nysds/nys-processlist/nys-processlistitem";
import "@nysds/nys-processlist/nys-processlistitem";

@ProxyCmp({ inputs: ["description", "label"] })
@Component({
  selector: "nys-processlistitem",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["description", "label"],
})
export class NysProcesslistitemComponent {
  protected readonly el: NysProcesslistitemElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysProcesslistitemComponent extends Pick<
  NysProcesslistitemElement,
  "description" | "label"
> {}
