/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysOption as NysOptionElement } from "@nysds/nys-select/nys-option";
import "@nysds/nys-select/nys-option";

@ProxyCmp({ inputs: ["disabled", "hidden", "label", "selected", "value"] })
@Component({
  selector: "nys-option",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["disabled", "hidden", "label", "selected", "value"],
})
export class NysOptionComponent {
  protected readonly el: NysOptionElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysOptionComponent extends Pick<
  NysOptionElement,
  "disabled" | "hidden" | "label" | "selected" | "value"
> {}
