/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysVerticalnav as NysVerticalnavElement } from "@nysds/nys-verticalnav";
import "@nysds/nys-verticalnav";

@ProxyCmp({
  inputs: ["expanded", "heading", "headingLevel", "hideHeading", "id"],
})
@Component({
  selector: "nys-verticalnav",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["expanded", "heading", "headingLevel", "hideHeading", "id"],
})
export class NysVerticalnavComponent {
  protected readonly el: NysVerticalnavElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysVerticalnavComponent extends Pick<
  NysVerticalnavElement,
  "expanded" | "heading" | "headingLevel" | "hideHeading" | "id"
> {}
