/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysBreadcrumbs as NysBreadcrumbsElement } from "@nysds/nys-breadcrumbs";
import "@nysds/nys-breadcrumbs";

@ProxyCmp({
  inputs: [
    "ariaLabel",
    "backToParent",
    "backgroundBar",
    "collapsed",
    "disabled",
    "id",
    "size",
  ],
})
@Component({
  selector: "nys-breadcrumbs",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "ariaLabel",
    "backToParent",
    "backgroundBar",
    "collapsed",
    "disabled",
    "id",
    "size",
  ],
  outputs: ["nys-breadcrumbs-expand", "nys-expand"],
})
export class NysBreadcrumbsComponent {
  protected readonly el: NysBreadcrumbsElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, ["nys-breadcrumbs-expand", "nys-expand"]);
  }
}

export declare interface NysBreadcrumbsComponent extends Pick<
  NysBreadcrumbsElement,
  | "ariaLabel"
  | "backToParent"
  | "backgroundBar"
  | "collapsed"
  | "disabled"
  | "id"
  | "size"
> {
  "nys-breadcrumbs-expand": Observable<CustomEvent>;
  "nys-expand": Observable<CustomEvent>;
}
