/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysAccordion as NysAccordionElement } from "@nysds/nys-accordion";
import "@nysds/nys-accordion";

@ProxyCmp({ inputs: ["bordered", "headingLevel", "id", "singleSelect"] })
@Component({
  selector: "nys-accordion",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["bordered", "headingLevel", "id", "singleSelect"],
})
export class NysAccordionComponent {
  protected readonly el: NysAccordionElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysAccordionComponent extends Pick<
  NysAccordionElement,
  "bordered" | "headingLevel" | "id" | "singleSelect"
> {}
