/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysRadiogroup as NysRadiogroupElement } from "@nysds/nys-radiobutton";
import "@nysds/nys-radiobutton";

@ProxyCmp({
  inputs: [
    "description",
    "errorMessage",
    "form",
    "id",
    "label",
    "name",
    "optional",
    "required",
    "showError",
    "size",
    "tile",
    "tooltip",
  ],
})
@Component({
  selector: "nys-radiogroup",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "description",
    "errorMessage",
    "form",
    "id",
    "label",
    "name",
    "optional",
    "required",
    "showError",
    "size",
    "tile",
    "tooltip",
  ],
  outputs: ["nys-change", "nys-other-input"],
})
export class NysRadiogroupComponent {
  protected readonly el: NysRadiogroupElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, ["nys-change", "nys-other-input"]);
  }
}

export declare interface NysRadiogroupComponent extends Pick<
  NysRadiogroupElement,
  | "description"
  | "errorMessage"
  | "form"
  | "id"
  | "label"
  | "name"
  | "optional"
  | "required"
  | "showError"
  | "size"
  | "tile"
  | "tooltip"
> {
  "nys-change": Observable<CustomEvent>;
  "nys-other-input": Observable<CustomEvent>;
}
