/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysPagination as NysPaginationElement } from "@nysds/nys-pagination";
import "@nysds/nys-pagination";

@ProxyCmp({ inputs: ["currentPage", "id", "name", "totalPages"] })
@Component({
  selector: "nys-pagination",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["currentPage", "id", "name", "totalPages"],
  outputs: ["nys-change"],
})
export class NysPaginationComponent {
  protected readonly el: NysPaginationElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, ["nys-change"]);
  }
}

export declare interface NysPaginationComponent extends Pick<
  NysPaginationElement,
  "currentPage" | "id" | "name" | "totalPages"
> {
  "nys-change": Observable<CustomEvent>;
}
