/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysTabgroup as NysTabgroupElement } from "@nysds/nys-tab/nys-tabgroup";
import "@nysds/nys-tab/nys-tabgroup";

@ProxyCmp({ inputs: ["id", "name"] })
@Component({
  selector: "nys-tabgroup",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["id", "name"],
})
export class NysTabgroupComponent {
  protected readonly el: NysTabgroupElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysTabgroupComponent extends Pick<
  NysTabgroupElement,
  "id" | "name"
> {}
