/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysBadge as NysBadgeElement } from "@nysds/nys-badge";
import "@nysds/nys-badge";

@ProxyCmp({
  inputs: [
    "id",
    "intent",
    "label",
    "name",
    "prefixIcon",
    "prefixLabel",
    "size",
    "srText",
    "strong",
    "suffixIcon",
  ],
})
@Component({
  selector: "nys-badge",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "id",
    "intent",
    "label",
    "name",
    "prefixIcon",
    "prefixLabel",
    "size",
    "srText",
    "strong",
    "suffixIcon",
  ],
})
export class NysBadgeComponent {
  protected readonly el: NysBadgeElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysBadgeComponent extends Pick<
  NysBadgeElement,
  | "id"
  | "intent"
  | "label"
  | "name"
  | "prefixIcon"
  | "prefixLabel"
  | "size"
  | "srText"
  | "strong"
  | "suffixIcon"
> {}
