/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysModal as NysModalElement } from "@nysds/nys-modal";
import "@nysds/nys-modal";

@ProxyCmp({
  inputs: [
    "ariaLabel",
    "heading",
    "id",
    "mandatory",
    "open",
    "subheading",
    "width",
  ],
})
@Component({
  selector: "nys-modal",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "ariaLabel",
    "heading",
    "id",
    "mandatory",
    "open",
    "subheading",
    "width",
  ],
  outputs: ["nys-close", "nys-open"],
})
export class NysModalComponent {
  protected readonly el: NysModalElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, ["nys-close", "nys-open"]);
  }
}

export declare interface NysModalComponent extends Pick<
  NysModalElement,
  "ariaLabel" | "heading" | "id" | "mandatory" | "open" | "subheading" | "width"
> {
  "nys-close": Observable<CustomEvent>;
  "nys-open": Observable<CustomEvent>;
}
