/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  HostListener,
  NgZone,
  forwardRef,
} from "@angular/core";
import { NG_VALUE_ACCESSOR } from "@angular/forms";
import type { ControlValueAccessor } from "@angular/forms";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysTextarea as NysTextareaElement } from "@nysds/nys-textarea";
import "@nysds/nys-textarea";

@ProxyCmp({
  inputs: [
    "ariaLabel",
    "description",
    "disabled",
    "errorMessage",
    "form",
    "id",
    "inverted",
    "label",
    "maxlength",
    "name",
    "optional",
    "placeholder",
    "readonly",
    "required",
    "resize",
    "rows",
    "showError",
    "tooltip",
    "value",
    "width",
  ],
})
@Component({
  selector: "nys-textarea",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "ariaLabel",
    "description",
    "disabled",
    "errorMessage",
    "form",
    "id",
    "inverted",
    "label",
    "maxlength",
    "name",
    "optional",
    "placeholder",
    "readonly",
    "required",
    "resize",
    "rows",
    "showError",
    "tooltip",
    "value",
    "width",
  ],
  outputs: [
    "nys-blur",
    "nys-focus",
    "nys-input",
    "nys-select",
    "nys-selectionchange",
  ],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => NysTextareaComponent),
      multi: true,
    },
  ],
})
export class NysTextareaComponent implements ControlValueAccessor {
  protected readonly el: NysTextareaElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, [
      "nys-blur",
      "nys-focus",
      "nys-input",
      "nys-select",
      "nys-selectionchange",
    ]);
  }

  // ControlValueAccessor — bridges Angular forms (ngModel / formControlName)
  // to the element's `value` property and its `nys-input` event.
  private onChange: (value: any) => void = () => {};
  private onTouched: () => void = () => {};

  writeValue(value: any): void {
    this.el.value = value ?? "";
  }

  registerOnChange(fn: (value: any) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.el.disabled = isDisabled;
  }

  @HostListener("nys-input")
  protected handleChangeEvent(): void {
    this.onChange(this.el.value);
  }

  @HostListener("nys-blur")
  protected handleBlurEvent(): void {
    this.onTouched();
  }
}

export declare interface NysTextareaComponent extends Pick<
  NysTextareaElement,
  | "ariaLabel"
  | "description"
  | "disabled"
  | "errorMessage"
  | "form"
  | "id"
  | "inverted"
  | "label"
  | "maxlength"
  | "name"
  | "optional"
  | "placeholder"
  | "readonly"
  | "required"
  | "resize"
  | "rows"
  | "showError"
  | "tooltip"
  | "value"
  | "width"
> {
  "nys-blur": Observable<CustomEvent>;
  "nys-focus": Observable<CustomEvent>;
  "nys-input": Observable<CustomEvent>;
  "nys-select": Observable<CustomEvent>;
  "nys-selectionchange": Observable<CustomEvent>;
}
