/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysTabpanel as NysTabpanelElement } from "@nysds/nys-tab";
import "@nysds/nys-tab";

@ProxyCmp({ inputs: ["id"] })
@Component({
  selector: "nys-tabpanel",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["id"],
})
export class NysTabpanelComponent {
  protected readonly el: NysTabpanelElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysTabpanelComponent extends Pick<
  NysTabpanelElement,
  "id"
> {}
