/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  HostListener,
  NgZone,
  forwardRef,
} from "@angular/core";
import { NG_VALUE_ACCESSOR } from "@angular/forms";
import type { ControlValueAccessor } from "@angular/forms";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysCombobox as NysComboboxElement } from "@nysds/nys-combobox";
import "@nysds/nys-combobox";

@ProxyCmp({
  inputs: [
    "description",
    "disabled",
    "errorMessage",
    "form",
    "id",
    "inverted",
    "label",
    "name",
    "optional",
    "required",
    "showError",
    "tooltip",
    "value",
    "width",
  ],
})
@Component({
  selector: "nys-combobox",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "description",
    "disabled",
    "errorMessage",
    "form",
    "id",
    "inverted",
    "label",
    "name",
    "optional",
    "required",
    "showError",
    "tooltip",
    "value",
    "width",
  ],
  outputs: ["nys-blur", "nys-change", "nys-focus", "nys-input"],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => NysComboboxComponent),
      multi: true,
    },
  ],
})
export class NysComboboxComponent implements ControlValueAccessor {
  protected readonly el: NysComboboxElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, [
      "nys-blur",
      "nys-change",
      "nys-focus",
      "nys-input",
    ]);
  }

  // ControlValueAccessor — bridges Angular forms (ngModel / formControlName)
  // to the element's `value` property and its `nys-change` event.
  private onChange: (value: any) => void = () => {};
  private onTouched: () => void = () => {};

  writeValue(value: any): void {
    this.el.value = value ?? "";
  }

  registerOnChange(fn: (value: any) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.el.disabled = isDisabled;
  }

  @HostListener("nys-change")
  protected handleChangeEvent(): void {
    this.onChange(this.el.value);
  }

  @HostListener("nys-blur")
  protected handleBlurEvent(): void {
    this.onTouched();
  }
}

export declare interface NysComboboxComponent extends Pick<
  NysComboboxElement,
  | "description"
  | "disabled"
  | "errorMessage"
  | "form"
  | "id"
  | "inverted"
  | "label"
  | "name"
  | "optional"
  | "required"
  | "showError"
  | "tooltip"
  | "value"
  | "width"
> {
  "nys-blur": Observable<CustomEvent>;
  "nys-change": Observable<CustomEvent>;
  "nys-focus": Observable<CustomEvent>;
  "nys-input": Observable<CustomEvent>;
}
