/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysLabel as NysLabelElement } from "@nysds/nys-label";
import "@nysds/nys-label";

@ProxyCmp({
  inputs: ["description", "flag", "id", "inverted", "label", "tooltip"],
})
@Component({
  selector: "nys-label",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["description", "flag", "id", "inverted", "label", "tooltip"],
  outputs: ["nys-label-click"],
})
export class NysLabelComponent {
  protected readonly el: NysLabelElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, ["nys-label-click"]);
  }
}

export declare interface NysLabelComponent extends Pick<
  NysLabelElement,
  "description" | "flag" | "id" | "inverted" | "label" | "tooltip"
> {
  "nys-label-click": Observable<CustomEvent>;
}
