/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysAlert as NysAlertElement } from "@nysds/nys-alert";
import "@nysds/nys-alert";

@ProxyCmp({
  inputs: [
    "ariaAttributes",
    "dismissible",
    "duration",
    "heading",
    "icon",
    "id",
    "primaryAction",
    "primaryLabel",
    "secondaryAction",
    "secondaryLabel",
    "text",
    "type",
  ],
})
@Component({
  selector: "nys-alert",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "ariaAttributes",
    "dismissible",
    "duration",
    "heading",
    "icon",
    "id",
    "primaryAction",
    "primaryLabel",
    "secondaryAction",
    "secondaryLabel",
    "text",
    "type",
  ],
  outputs: ["nys-close"],
})
export class NysAlertComponent {
  protected readonly el: NysAlertElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, ["nys-close"]);
  }
}

export declare interface NysAlertComponent extends Pick<
  NysAlertElement,
  | "ariaAttributes"
  | "dismissible"
  | "duration"
  | "heading"
  | "icon"
  | "id"
  | "primaryAction"
  | "primaryLabel"
  | "secondaryAction"
  | "secondaryLabel"
  | "text"
  | "type"
> {
  "nys-close": Observable<CustomEvent>;
}
