/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysGlobalFooter as NysGlobalFooterElement } from "@nysds/nys-globalfooter";
import "@nysds/nys-globalfooter";

@ProxyCmp({
  inputs: [
    "agencyName",
    "agencySubheading",
    "homepageLink",
    "id",
    "landmarkLabel",
  ],
})
@Component({
  selector: "nys-globalfooter",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "agencyName",
    "agencySubheading",
    "homepageLink",
    "id",
    "landmarkLabel",
  ],
})
export class NysGlobalFooterComponent {
  protected readonly el: NysGlobalFooterElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysGlobalFooterComponent extends Pick<
  NysGlobalFooterElement,
  "agencyName" | "agencySubheading" | "homepageLink" | "id" | "landmarkLabel"
> {}
