/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysTab as NysTabElement } from "@nysds/nys-tab";
import "@nysds/nys-tab";

@ProxyCmp({ inputs: ["disabled", "id", "label", "selected"] })
@Component({
  selector: "nys-tab",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["disabled", "id", "label", "selected"],
  outputs: ["nys-tab-blur", "nys-tab-focus", "nys-tab-select"],
})
export class NysTabComponent {
  protected readonly el: NysTabElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, [
      "nys-tab-blur",
      "nys-tab-focus",
      "nys-tab-select",
    ]);
  }
}

export declare interface NysTabComponent extends Pick<
  NysTabElement,
  "disabled" | "id" | "label" | "selected"
> {
  "nys-tab-blur": Observable<CustomEvent>;
  "nys-tab-focus": Observable<CustomEvent>;
  "nys-tab-select": Observable<CustomEvent>;
}
