/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  HostListener,
  NgZone,
  forwardRef,
} from "@angular/core";
import { NG_VALUE_ACCESSOR } from "@angular/forms";
import type { ControlValueAccessor } from "@angular/forms";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysCheckbox as NysCheckboxElement } from "@nysds/nys-checkbox";
import "@nysds/nys-checkbox";

@ProxyCmp({
  inputs: [
    "checked",
    "description",
    "disabled",
    "errorMessage",
    "form",
    "groupExist",
    "hideLabel",
    "id",
    "label",
    "labelledby",
    "name",
    "other",
    "required",
    "showError",
    "showOtherError",
    "size",
    "tile",
    "tooltip",
    "value",
  ],
})
@Component({
  selector: "nys-checkbox",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "checked",
    "description",
    "disabled",
    "errorMessage",
    "form",
    "groupExist",
    "hideLabel",
    "id",
    "label",
    "labelledby",
    "name",
    "other",
    "required",
    "showError",
    "showOtherError",
    "size",
    "tile",
    "tooltip",
    "value",
  ],
  outputs: [
    "nys-blur",
    "nys-change",
    "nys-error",
    "nys-error-clear",
    "nys-focus",
    "nys-other-input",
  ],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => NysCheckboxComponent),
      multi: true,
    },
  ],
})
export class NysCheckboxComponent implements ControlValueAccessor {
  protected readonly el: NysCheckboxElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, [
      "nys-blur",
      "nys-change",
      "nys-error",
      "nys-error-clear",
      "nys-focus",
      "nys-other-input",
    ]);
  }

  // ControlValueAccessor — bridges Angular forms (ngModel / formControlName)
  // to the element's `checked` property and its `nys-change` event.
  private onChange: (value: any) => void = () => {};
  private onTouched: () => void = () => {};

  writeValue(value: any): void {
    this.el.checked = !!value;
  }

  registerOnChange(fn: (value: any) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.el.disabled = isDisabled;
  }

  @HostListener("nys-change")
  protected handleChangeEvent(): void {
    this.onChange(this.el.checked);
  }

  @HostListener("nys-blur")
  protected handleBlurEvent(): void {
    this.onTouched();
  }
}

export declare interface NysCheckboxComponent extends Pick<
  NysCheckboxElement,
  | "checked"
  | "description"
  | "disabled"
  | "errorMessage"
  | "form"
  | "groupExist"
  | "hideLabel"
  | "id"
  | "label"
  | "labelledby"
  | "name"
  | "other"
  | "required"
  | "showError"
  | "showOtherError"
  | "size"
  | "tile"
  | "tooltip"
  | "value"
> {
  "nys-blur": Observable<CustomEvent>;
  "nys-change": Observable<CustomEvent>;
  "nys-error": Observable<CustomEvent>;
  "nys-error-clear": Observable<CustomEvent>;
  "nys-focus": Observable<CustomEvent>;
  "nys-other-input": Observable<CustomEvent>;
}
