/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysCheckboxgroup as NysCheckboxgroupElement } from "@nysds/nys-checkbox";
import "@nysds/nys-checkbox";

@ProxyCmp({
  inputs: [
    "description",
    "errorMessage",
    "form",
    "id",
    "label",
    "name",
    "optional",
    "required",
    "showError",
    "size",
    "tile",
    "tooltip",
  ],
})
@Component({
  selector: "nys-checkboxgroup",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "description",
    "errorMessage",
    "form",
    "id",
    "label",
    "name",
    "optional",
    "required",
    "showError",
    "size",
    "tile",
    "tooltip",
  ],
})
export class NysCheckboxgroupComponent {
  protected readonly el: NysCheckboxgroupElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysCheckboxgroupComponent extends Pick<
  NysCheckboxgroupElement,
  | "description"
  | "errorMessage"
  | "form"
  | "id"
  | "label"
  | "name"
  | "optional"
  | "required"
  | "showError"
  | "size"
  | "tile"
  | "tooltip"
> {}
