/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysTooltip as NysTooltipElement } from "@nysds/nys-tooltip";
import "@nysds/nys-tooltip";

@ProxyCmp({ inputs: ["for", "id", "inverted", "position", "text"] })
@Component({
  selector: "nys-tooltip",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["for", "id", "inverted", "position", "text"],
})
export class NysTooltipComponent {
  protected readonly el: NysTooltipElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysTooltipComponent extends Pick<
  NysTooltipElement,
  "for" | "id" | "inverted" | "position" | "text"
> {}
