/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysTable as NysTableElement } from "@nysds/nys-table";
import "@nysds/nys-table";

@ProxyCmp({
  inputs: ["bordered", "download", "id", "name", "sortable", "striped"],
})
@Component({
  selector: "nys-table",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["bordered", "download", "id", "name", "sortable", "striped"],
  outputs: ["nys-click", "nys-column-sort"],
})
export class NysTableComponent {
  protected readonly el: NysTableElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, ["nys-click", "nys-column-sort"]);
  }
}

export declare interface NysTableComponent extends Pick<
  NysTableElement,
  "bordered" | "download" | "id" | "name" | "sortable" | "striped"
> {
  "nys-click": Observable<CustomEvent>;
  "nys-column-sort": Observable<CustomEvent>;
}
