/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysIconlistitem as NysIconlistitemElement } from "@nysds/nys-iconlist";
import "@nysds/nys-iconlist";

@ProxyCmp({ inputs: ["divider", "icon"] })
@Component({
  selector: "nys-iconlistitem",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["divider", "icon"],
})
export class NysIconlistitemComponent {
  protected readonly el: NysIconlistitemElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysIconlistitemComponent extends Pick<
  NysIconlistitemElement,
  "divider" | "icon"
> {}
