/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysSkipnav as NysSkipnavElement } from "@nysds/nys-skipnav";
import "@nysds/nys-skipnav";

@ProxyCmp({ inputs: ["href", "id"] })
@Component({
  selector: "nys-skipnav",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["href", "id"],
})
export class NysSkipnavComponent {
  protected readonly el: NysSkipnavElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysSkipnavComponent extends Pick<
  NysSkipnavElement,
  "href" | "id"
> {}
