/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysErrorMessage as NysErrorMessageElement } from "@nysds/nys-errormessage";
import "@nysds/nys-errormessage";

@ProxyCmp({ inputs: ["errorMessage", "id", "showDivider", "showError"] })
@Component({
  selector: "nys-errormessage",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["errorMessage", "id", "showDivider", "showError"],
})
export class NysErrorMessageComponent {
  protected readonly el: NysErrorMessageElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysErrorMessageComponent extends Pick<
  NysErrorMessageElement,
  "errorMessage" | "id" | "showDivider" | "showError"
> {}
