/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysUnavFooter as NysUnavFooterElement } from "@nysds/nys-unavfooter";
import "@nysds/nys-unavfooter";

@ProxyCmp({ inputs: ["landmarkLabel"] })
@Component({
  selector: "nys-unavfooter",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["landmarkLabel"],
})
export class NysUnavFooterComponent {
  protected readonly el: NysUnavFooterElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysUnavFooterComponent extends Pick<
  NysUnavFooterElement,
  "landmarkLabel"
> {}
