/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysStepper as NysStepperElement } from "@nysds/nys-stepper";
import "@nysds/nys-stepper";

@ProxyCmp({
  inputs: ["counterText", "id", "isCompactExpanded", "label", "name"],
})
@Component({
  selector: "nys-stepper",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["counterText", "id", "isCompactExpanded", "label", "name"],
})
export class NysStepperComponent {
  protected readonly el: NysStepperElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysStepperComponent extends Pick<
  NysStepperElement,
  "counterText" | "id" | "isCompactExpanded" | "label" | "name"
> {}
