/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysOption as NysOptionElement } from "@nysds/nys-select";
import "@nysds/nys-select";

@ProxyCmp({ inputs: ["disabled", "hidden", "label", "selected", "value"] })
@Component({
  selector: "nys-option",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["disabled", "hidden", "label", "selected", "value"],
})
export class NysOptionComponent {
  protected readonly el: NysOptionElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysOptionComponent extends Pick<
  NysOptionElement,
  "disabled" | "hidden" | "label" | "selected" | "value"
> {}
