/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysCard as NysCardElement } from "@nysds/nys-card";
import "@nysds/nys-card";

@ProxyCmp({
  inputs: [
    "description",
    "elevated",
    "heading",
    "headingLevel",
    "href",
    "id",
    "inset",
    "onClick",
    "preheading",
    "subheading",
    "target",
  ],
})
@Component({
  selector: "nys-card",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "description",
    "elevated",
    "heading",
    "headingLevel",
    "href",
    "id",
    "inset",
    "onClick",
    "preheading",
    "subheading",
    "target",
  ],
  outputs: ["nys-blur", "nys-click", "nys-focus"],
})
export class NysCardComponent {
  protected readonly el: NysCardElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, ["nys-blur", "nys-click", "nys-focus"]);
  }
}

export declare interface NysCardComponent extends Pick<
  NysCardElement,
  | "description"
  | "elevated"
  | "heading"
  | "headingLevel"
  | "href"
  | "id"
  | "inset"
  | "onClick"
  | "preheading"
  | "subheading"
  | "target"
> {
  "nys-blur": Observable<CustomEvent>;
  "nys-click": Observable<CustomEvent>;
  "nys-focus": Observable<CustomEvent>;
}
