/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysAccordionItem as NysAccordionItemElement } from "@nysds/nys-accordion/nys-accordionitem";
import "@nysds/nys-accordion/nys-accordionitem";

@ProxyCmp({ inputs: ["bordered", "expanded", "heading", "headingLevel", "id"] })
@Component({
  selector: "nys-accordionitem",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: ["bordered", "expanded", "heading", "headingLevel", "id"],
  outputs: ["nys-accordionitem-toggle"],
})
export class NysAccordionItemComponent {
  protected readonly el: NysAccordionItemElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, ["nys-accordionitem-toggle"]);
  }
}

export declare interface NysAccordionItemComponent extends Pick<
  NysAccordionItemElement,
  "bordered" | "expanded" | "heading" | "headingLevel" | "id"
> {
  "nys-accordionitem-toggle": Observable<CustomEvent>;
}
