/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysButton as NysButtonElement } from "@nysds/nys-button";
import "@nysds/nys-button";

@ProxyCmp({
  inputs: [
    "ariaControls",
    "ariaCurrent",
    "ariaDescribedBy",
    "ariaExpanded",
    "circle",
    "disabled",
    "form",
    "fullWidth",
    "href",
    "icon",
    "id",
    "inverted",
    "label",
    "name",
    "onClick",
    "prefixIcon",
    "size",
    "suffixIcon",
    "target",
    "type",
    "value",
    "variant",
  ],
})
@Component({
  selector: "nys-button",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "ariaControls",
    "ariaCurrent",
    "ariaDescribedBy",
    "ariaExpanded",
    "circle",
    "disabled",
    "form",
    "fullWidth",
    "href",
    "icon",
    "id",
    "inverted",
    "label",
    "name",
    "onClick",
    "prefixIcon",
    "size",
    "suffixIcon",
    "target",
    "type",
    "value",
    "variant",
  ],
  outputs: ["nys-blur", "nys-click", "nys-focus"],
})
export class NysButtonComponent {
  protected readonly el: NysButtonElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, ["nys-blur", "nys-click", "nys-focus"]);
  }
}

export declare interface NysButtonComponent extends Pick<
  NysButtonElement,
  | "ariaControls"
  | "ariaCurrent"
  | "ariaDescribedBy"
  | "ariaExpanded"
  | "circle"
  | "disabled"
  | "form"
  | "fullWidth"
  | "href"
  | "icon"
  | "id"
  | "inverted"
  | "label"
  | "name"
  | "onClick"
  | "prefixIcon"
  | "size"
  | "suffixIcon"
  | "target"
  | "type"
  | "value"
  | "variant"
> {
  "nys-blur": Observable<CustomEvent>;
  "nys-click": Observable<CustomEvent>;
  "nys-focus": Observable<CustomEvent>;
}
