/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import type { Observable } from "rxjs";
import { ProxyCmp, proxyOutputs } from "./utils";
import type { NysUnavHeader as NysUnavHeaderElement } from "@nysds/nys-unavheader";
import "@nysds/nys-unavheader";

@ProxyCmp({
  inputs: [
    "hideSearch",
    "hideTranslate",
    "isSearchFocused",
    "landmarkLabel",
    "languageVisible",
    "languages",
    "searchDropdownVisible",
    "searchUrl",
    "trustbarVisible",
  ],
})
@Component({
  selector: "nys-unavheader",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "hideSearch",
    "hideTranslate",
    "isSearchFocused",
    "landmarkLabel",
    "languageVisible",
    "languages",
    "searchDropdownVisible",
    "searchUrl",
    "trustbarVisible",
  ],
  outputs: ["nys-language-select", "nys-search-submit"],
})
export class NysUnavHeaderComponent {
  protected readonly el: NysUnavHeaderElement;

  constructor(
    changeDetector: ChangeDetectorRef,
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    // The wrapper renders nothing of its own (ng-content only); the custom
    // element manages its own rendering, so Angular CD is detached entirely.
    changeDetector.detach();
    this.el = elementRef.nativeElement;
    proxyOutputs(this, this.el, ["nys-language-select", "nys-search-submit"]);
  }
}

export declare interface NysUnavHeaderComponent extends Pick<
  NysUnavHeaderElement,
  | "hideSearch"
  | "hideTranslate"
  | "isSearchFocused"
  | "landmarkLabel"
  | "languageVisible"
  | "languages"
  | "searchDropdownVisible"
  | "searchUrl"
  | "trustbarVisible"
> {
  "nys-language-select": Observable<CustomEvent>;
  "nys-search-submit": Observable<CustomEvent>;
}
