/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
} from "@angular/core";
import { ProxyCmp } from "./utils";
import type { NysGlobalHeader as NysGlobalHeaderElement } from "@nysds/nys-globalheader";
import "@nysds/nys-globalheader";

@ProxyCmp({
  inputs: [
    "agencyName",
    "appName",
    "homepageLink",
    "id",
    "landmarkLabel",
    "nysLogo",
  ],
})
@Component({
  selector: "nys-globalheader",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  inputs: [
    "agencyName",
    "appName",
    "homepageLink",
    "id",
    "landmarkLabel",
    "nysLogo",
  ],
})
export class NysGlobalHeaderComponent {
  protected readonly el: NysGlobalHeaderElement;

  constructor(
    elementRef: ElementRef,
    protected readonly z: NgZone,
  ) {
    this.el = elementRef.nativeElement;
  }
}

export declare interface NysGlobalHeaderComponent extends Pick<
  NysGlobalHeaderElement,
  "agencyName" | "appName" | "homepageLink" | "id" | "landmarkLabel" | "nysLogo"
> {}
