/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import { NysAccordionComponent } from "./nys-accordion.component";
import { NysAccordionItemComponent } from "./nys-accordionitem.component";
import { NysAlertComponent } from "./nys-alert.component";
import { NysAvatarComponent } from "./nys-avatar.component";
import { NysBacktotopComponent } from "./nys-backtotop.component";
import { NysBadgeComponent } from "./nys-badge.component";
import { NysBreadcrumbsComponent } from "./nys-breadcrumbs.component";
import { NysButtonComponent } from "./nys-button.component";
import { NysCardComponent } from "./nys-card.component";
import { NysCheckboxComponent } from "./nys-checkbox.component";
import { NysCheckboxgroupComponent } from "./nys-checkboxgroup.component";
import { NysComboboxComponent } from "./nys-combobox.component";
import { NysDatepickerComponent } from "./nys-datepicker.component";
import { NysDividerComponent } from "./nys-divider.component";
import { NysDropdownMenuComponent } from "./nys-dropdownmenu.component";
import { NysDropdownMenuItemComponent } from "./nys-dropdownmenuitem.component";
import { NysErrorMessageComponent } from "./nys-errormessage.component";
import { NysFileinputComponent } from "./nys-fileinput.component";
import { NysFileItemComponent } from "./nys-fileitem.component";
import { NysGlobalFooterComponent } from "./nys-globalfooter.component";
import { NysGlobalHeaderComponent } from "./nys-globalheader.component";
import { NysIconComponent } from "./nys-icon.component";
import { NysIconlistComponent } from "./nys-iconlist.component";
import { NysIconlistitemComponent } from "./nys-iconlistitem.component";
import { NysLabelComponent } from "./nys-label.component";
import { NysModalComponent } from "./nys-modal.component";
import { NysOptionComponent } from "./nys-option.component";
import { NysPaginationComponent } from "./nys-pagination.component";
import { NysProcesslistComponent } from "./nys-processlist.component";
import { NysProcesslistitemComponent } from "./nys-processlistitem.component";
import { NysRadiobuttonComponent } from "./nys-radiobutton.component";
import { NysRadiogroupComponent } from "./nys-radiogroup.component";
import { NysSelectComponent } from "./nys-select.component";
import { NysSkipnavComponent } from "./nys-skipnav.component";
import { NysStepComponent } from "./nys-step.component";
import { NysStepperComponent } from "./nys-stepper.component";
import { NysTabComponent } from "./nys-tab.component";
import { NysTabgroupComponent } from "./nys-tabgroup.component";
import { NysTableComponent } from "./nys-table.component";
import { NysTabpanelComponent } from "./nys-tabpanel.component";
import { NysTextareaComponent } from "./nys-textarea.component";
import { NysTextinputComponent } from "./nys-textinput.component";
import { NysToggleComponent } from "./nys-toggle.component";
import { NysTooltipComponent } from "./nys-tooltip.component";
import { NysUnavFooterComponent } from "./nys-unavfooter.component";
import { NysUnavHeaderComponent } from "./nys-unavheader.component";
import { NysVerticalnavComponent } from "./nys-verticalnav.component";
import { NysVerticalnavGroupComponent } from "./nys-verticalnavgroup.component";
import { NysVideoComponent } from "./nys-video.component";

/** Every NYSDS wrapper component — spread into a standalone component's `imports`. */
export const NYSDS_COMPONENTS = [
  NysAccordionComponent,
  NysAccordionItemComponent,
  NysAlertComponent,
  NysAvatarComponent,
  NysBacktotopComponent,
  NysBadgeComponent,
  NysBreadcrumbsComponent,
  NysButtonComponent,
  NysCardComponent,
  NysCheckboxComponent,
  NysCheckboxgroupComponent,
  NysComboboxComponent,
  NysDatepickerComponent,
  NysDividerComponent,
  NysDropdownMenuComponent,
  NysDropdownMenuItemComponent,
  NysErrorMessageComponent,
  NysFileinputComponent,
  NysFileItemComponent,
  NysGlobalFooterComponent,
  NysGlobalHeaderComponent,
  NysIconComponent,
  NysIconlistComponent,
  NysIconlistitemComponent,
  NysLabelComponent,
  NysModalComponent,
  NysOptionComponent,
  NysPaginationComponent,
  NysProcesslistComponent,
  NysProcesslistitemComponent,
  NysRadiobuttonComponent,
  NysRadiogroupComponent,
  NysSelectComponent,
  NysSkipnavComponent,
  NysStepComponent,
  NysStepperComponent,
  NysTabComponent,
  NysTabgroupComponent,
  NysTableComponent,
  NysTabpanelComponent,
  NysTextareaComponent,
  NysTextinputComponent,
  NysToggleComponent,
  NysTooltipComponent,
  NysUnavFooterComponent,
  NysUnavHeaderComponent,
  NysVerticalnavComponent,
  NysVerticalnavGroupComponent,
  NysVideoComponent,
] as const;
