/* AUTO-GENERATED by src/scripts/cem-angular-plugin.mjs — do not edit.
 * Regenerate with `npm run cem`. */

import { fromEvent } from "rxjs";

/**
 * Defines each input as a getter/setter pair on the wrapper component's
 * prototype that reads/writes the underlying custom element's property.
 *
 * Why: when an Angular component is attached to an element, template bindings
 * like `[expanded]="true"` set the *component's* property — the DOM element
 * never sees the value. These accessors forward every write to
 * `this.el` (the host custom element) so the Lit component reacts, and
 * every read reflects the element's live state.
 *
 * Writes run outside Angular's zone: setting a Lit reactive property
 * schedules an async re-render inside the element, which Angular's change
 * detection has no interest in.
 */
export const proxyInputs = (componentClass: any, inputs: string[]): void => {
  const prototype = componentClass.prototype;
  inputs.forEach((name) => {
    Object.defineProperty(prototype, name, {
      get() {
        return this.el[name];
      },
      set(value: any) {
        this.z.runOutsideAngular(() => (this.el[name] = value));
      },
      configurable: true,
    });
  });
};

/**
 * Exposes the element's CustomEvents as Angular-bindable outputs.
 *
 * Assigning `fromEvent(el, "nys-change")` to the component property named
 * "nys-change" makes `(nys-change)="handler($event)"` work: Angular
 * subscribes to whatever Subscribable it finds on the declared output
 * property, and the handler receives the original CustomEvent (detail
 * included). Listening happens on the element itself, so nothing is lost
 * to shadow-DOM retargeting.
 */
export const proxyOutputs = (
  instance: any,
  el: HTMLElement,
  events: string[],
): void => {
  events.forEach(
    (eventName) => (instance[eventName] = fromEvent(el, eventName)),
  );
};

/**
 * Class decorator that wires up `proxyInputs` once per component class
 * (prototype accessors only need to be defined once, not per instance).
 */
export function ProxyCmp(opts: { inputs?: string[] }) {
  return (componentClass: any) => {
    if (opts.inputs?.length) {
      proxyInputs(componentClass, opts.inputs);
    }
    return componentClass;
  };
}
